### PR TITLE
News Section Entry

### PR DESCRIPTION
**Pull request by StrKoulierakis**

### CODE REVIEW

**Review by MichaelRoeder — CHANGES_REQUESTED** [review]
Why do you created the file two times? I think the one in `pages/news` is correct while the other one should be removed.

**Comment by StrKoulierakis** [comment]
Thanks for letting me know, probably I uploaded by mistake, I will remove it

**Comment by StrKoulierakis** [comment]
Is it okay now?

**Review by MichaelRoeder — APPROVED** [review]
LGTM

**Pull request merged**
